### PR TITLE
Activate ACR build, image multistaging and hmcts runtime user

### PR DESCRIPTION
**Pull request by slyg**
# Description

This PR leverages on layers re-use to reduce the the docker image build time in CI.

Jira ticket: https://tools.hmcts.net/jira/browse/CNP-1131

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

The PR CI shows a decrease of build time of the docker image (1:20-ish min)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by slyg** [comment]
Thx for the approval, I can't merge on this project so I'll let one authorised users do it. Thx !

**Comment by slyg** [comment]
Hello, can an authorised user merge this branch please ? Thx !

**Comment by hosainnet** [comment]
Only @mrganeshraja @vianvi and @nsingamsetty can merge changes

**Comment by slyg** [comment]
Hi @mrganeshraja @vianvi and @nsingamsetty can one of you merge this PR please ? It is 8 days old now.

**Comment by slyg** [comment]
> Hi @mrganeshraja @vianvi and @nsingamsetty can one of you merge this PR please ? It is 8 days old now.

Should I get rid of this PR ? It brings docker build to last 1:30, same as unit tests+sonar.

**Pull request merged**
