### PR TITLE
DIV-3773 Added helm chart config

### PR DESCRIPTION
**Pull request by qzhou-hmcts**
# Description

Add helm chart config to deploy on AKS server.
Load secrets from volume
https://tools.hmcts.net/jira/browse/DIV-3773

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration**:

* Hardware:
* O/S and version:
* JDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by qzhou-hmcts** [comment]
@dtaylor7 done , this PR is add Helm chart config to deploy on AKS

**Comment by dtaylor7** [comment]
link to JIRA ticket?

**Comment by qzhou-hmcts** [comment]
@dtaylor7  DIV-3773 Added helm chart config #268

**Comment by dtaylor7** [comment]
comments wont show up in history, do like every other PR... helps when looking at history for debugging code e.g. https://github.com/hmcts/div-decree-nisi-frontend/pull/294

**Comment by hosainnet** [comment]
@dtaylor7 from your example (https://github.com/hmcts/div-decree-nisi-frontend/pull/294) I also think we should add the DIV number to the branch name, makes it easier when checking out branches locally

**Comment by hosainnet** [comment]
The same with commit messages

**Comment by hosainnet** [comment]
And PR titles

**Comment by qzhou-hmcts** [comment]
@dtaylor7  is in the header

**Comment by hosainnet** [comment]
@qzhou-hmcts there seems to be a problem with the yaml file?

**Comment by nsingamsetty** [comment]
RFE Helm chart stuff.

**Pull request merged**
